#author: Sekhar Reddy <sdreddy5@outlook.com>
---
- name: Create instance with specified arguments
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: create a new ec2 key pair
      ec2_key:
        name: custom_instance.pem
    - name: Launch instance
      ec2:
         key_name: custom_instance.pem
         group: security-group1
         instance_type: m1.small
         image: ami-05f222567ec8a3284
         wait: true
         region: us-east-2
         vpc_subnet_id: subnet-74abca38
         assign_public_ip: yes
      register: ec2_instance
      
    - debug:
        msg: "{{ ec2_instance }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 300
        state: started
      with_items: "{{ ec2_instance.instances }}"
---
- name: run command after server is up
  host: "{{ ec2_instance.instances.public_dns_name }}"
  gather_facts: true
  tasks:
  - name: run command 
    command: "ifconfig"
    register: command_result
  - name: print output
    debug:
        msg: "{{ command_result }}"